import{a as u,S as p}from"./assets/vendor-D-JDxJ7W.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&o(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();async function g(){try{const{data:s}=await u.get("https://portfolio-js.b.goit.study/api/reviews");return s}catch(s){console.error("Error",s)}}function m(s){const r=s.map(({_id:n,author:o,avatar_url:e,review:t})=>`
		<li class="swiper-slide review-card">
		<img src="${e}" alt="${o}"/>
		<div class="review-info">
		<h3>${o}</h3>
		<p>${t}</p>
		</div>
		</li>
		`).join("");return console.log(r),r}const f=document.querySelector(".reviews-container"),v=document.querySelector(".reviews-list"),a=document.querySelector(".reviews-error"),y=document.querySelector(".swiper-button-prev"),l=document.querySelector(".swiper-button-next");let c=!1;document.addEventListener("DOMContentLoaded",async()=>{try{let n=function(){y.toggleAttribute("disabled",r.isBeginning),l.toggleAttribute("disabled",r.isEnd)};const s=await g();if(console.log(s),!s||s.length===0){a.classList.remove("hidden"),a.classList.add("css-err-mes"),l.setAttribute("disabled","true"),c=!0;return}v.innerHTML=m(s);const r=new p(".swiper",{direction:"horizontal",loop:!1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},resizeObserver:!0,slidesPerView:1,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}}});r.on("slideChange",n),n()}catch(s){c=!0,console.error(s)}});const h=new IntersectionObserver(s=>{s.forEach(r=>{c&&r.isIntersecting&&alert("Виникла помилка, спробуйте трохи пізніше")})},{threshold:.1});h.observe(f);const w="/project-js-my-section/assets/Rectangle%204-DhhvSGKj.png",b="/project-js-my-section/assets/Rectangle%205-B1dJABMC.png",j="/project-js-my-section/assets/Rectangle%206-BNke5AMi.png",L="/project-js-my-section/assets/Rectangle%207-BM4erC3d.png",E="/project-js-my-section/assets/Rectangle%208-CX0zboi9.png",S="/project-js-my-section/assets/Rectangle%209-irqQ2rIt.png",q="/project-js-my-section/assets/first%20screen%201-Cy8Oikdc.png",O="/project-js-my-section/assets/Rectangle%2010-DLQwHKuu.png",C="/project-js-my-section/assets/Rectangle%2011-BIEC9Xhq.png",R="/project-js-my-section/assets/Rectangle%2012-DkoS0ite.png",I=[w,b,j,L,E,S,q,O,C,R],A=document.querySelectorAll(".marquee__inner"),d=document.querySelector(".covers-container");document.addEventListener("DOMContentLoaded",function(){function s(n){return n.slice().sort(()=>Math.random()-.5)}A.forEach(n=>{s(I).forEach(e=>{const t=document.createElement("li");t.classList.add("marquee__line");const i=document.createElement("img");i.src=e,t.appendChild(i),n.appendChild(t)})}),new IntersectionObserver(n=>{n.forEach(o=>{d.querySelectorAll(".marquee__line").forEach(t=>{o.isIntersecting?t.classList.add("covers-start-animation"):t.classList.remove("covers-start-animation")})})},{threshold:.1}).observe(d)});
//# sourceMappingURL=index.js.map
