import{a as u,S as d}from"./assets/vendor-D-JDxJ7W.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();async function a(){try{const{data:t}=await u.get("https://portfolio-js.b.goit.study/api/reviews");return t}catch(t){console.error("Error",t)}}function p(t){const o=t.map(({_id:s,author:i,avatar_url:e,review:r})=>`
		<li class="swiper-slide review-card">
		<img src="${e}" alt="${i}"/>
		<div class="review-info">
		<h3>${i}</h3>
		<p>${r}</p>
		</div>
		</li>
		`).join("");return console.log(o),o}const f=document.querySelector(".reviews-list"),m=document.querySelector(".reviews-error"),c=document.querySelector(".swiper-button-prev"),l=document.querySelector(".swiper-button-next");document.addEventListener("DOMContentLoaded",async()=>{try{let s=function(){o.isBeginning?c.setAttribute("disabled","true"):c.removeAttribute("disabled"),o.isEnd?l.setAttribute("disabled","true"):l.removeAttribute("disabled")};const t=await a();if(console.log(t),!t||t.length===0){m.classList.remove("hidden");return}f.innerHTML=p(t);const o=new d(".swiper",{direction:"horizontal",loop:!1,navigation:{nextEl:".swiper-button-next",prevEl:".swiper-button-prev"},keyboard:{enabled:!0,onlyInViewport:!0},mousewheel:{invert:!0},setWrapperSize:!0,slidesPerView:1,breakpoints:{768:{slidesPerView:2},1440:{slidesPerView:4}}});o.on("slideChange",s),updateButtonState()}catch(t){console.error(t)}});
//# sourceMappingURL=index.js.map
